### ISSUE TITLE
iOS - TintColor not working

### ISSUE THREAD

**Issue by brendonupson** [yurkinh/Plugin.Maui.SegmentedControl#1]
Hi,

I am trying to make the selected segment black with white text. Does not appear to be working.

Thanks,

Brendon.

**Comment by brendonupson** [comment]
Yours docs say default should be #007AFF, appears as white for me. TextColor works ok.

**Comment by yurkinh** [comment]
Hi @brendonupson 
Thanks for reporting an issue.
Check please version 1.0.4 which should appear in a minute.
It contains a fix for the mentioned issue

**Comment by brendonupson** [comment]
Sorry for the delay, busy wrestling with MAUI :-( Looks good now, thankyou!
