### ISSUE TITLE
Android Text Color

### ISSUE THREAD

**Issue by fxxxxw** [yurkinh/Plugin.Maui.SegmentedControl#2]
Hi, thank you for your plugin! I really like it :). I regocnized an issue (Android only) where the TextColor do not change to the normal TextColor after swapping between the tabs. The text keeps the TintColor after the first selection. It occurs also in light and dark mode. An example is shown in the picture (left: iOS, right: Android).

![segmentedcontrolissue](https://github.com/yurkinh/Plugin.Maui.SegmentedControl/assets/104002301/f6b81ecc-f309-4dfd-988f-b4f80869a281)

**Comment by yurkinh** [comment]
Hi @fxxxxw 
Good catch. I will take a look at it tomorrow

**Comment by yurkinh** [comment]
hello @fxxxxw 
Please check the latest nuget version 1.0.7. I have fixed Tint issue on Android and added support for NET8

**Comment by fxxxxw** [comment]
Hi @yurkinh, 
thank you, I appreciate that! Unfortunately, I am not able to do the update because I work on a .Net 7 Project and cannot upgrate to .Net 8 at the moment. However, I  need to upgrate to .Net 8 in the near future anyway :)

**Comment by yurkinh** [comment]
Hi @fxxxxw 
Oh! I thought that everybody had already jumped into .NET 8 boat due to fixes and better support))
Well if needed I can generate nuget  with fix but without .NET 8 support for you.
Or you can later update to v1.0.7 after migration to .NET 8

**Comment by fxxxxw** [comment]
Hi @yurkinh,
thank you for your offer but I will update the project to .Net 8 in the next couple of weeks anyway.

**Comment by yurkinh** [comment]
Good. Then I will close this issue
